# Generated by Django 5.2 on 2025-04-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newAddmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfBirth', models.DateField()),
                ('EducationQualification', models.CharField(max_length=80)),
            ],
        ),
    ]
