# Generated by Django 5.2 on 2025-04-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newAddmissions',
        ),
    ]
