# Generated by Django 5.2 on 2025-04-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scope', '0002_delete_newaddmissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=255)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('MemoryErrorobile_number', models.CharField(max_length=15)),
                ('Education_Qualification', models.CharField(max_length=255)),
                ('Guardian_Name', models.CharField(max_length=255)),
                ('Guardian_Occupation', models.CharField(max_length=255)),
                ('Guardian_Mobile', models.CharField(max_length=15)),
                ('Course', models.CharField(max_length=255)),
                ('Training_Mode', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Preferred_Timings', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Pin_code', models.CharField(max_length=10)),
            ],
        ),
    ]
