# Generated by Django 5.2 on 2025-04-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='MemoryErrorobile_number',
            new_name='Mobile_number',
        ),
    ]
