# Generated by Django 5.2 on 2025-04-29 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0004_rename_memoryerrorobile_number_student_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_Created_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
