# Generated by Django 5.2 on 2025-04-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0005_student_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_Updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
