# Generated by Django 5.2 on 2025-04-30 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0006_student_student_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_Updated_At',
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Created_At',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
