# Generated by Django 5.2 on 2025-04-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0007_remove_student_student_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Created_At',
            field=models.DateTimeField(editable=False),
        ),
    ]
