# Generated by Django 5.2 on 2025-05-01 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0008_alter_student_student_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=50)),
                ('Timings', models.CharField(max_length=50)),
                ('Batch', models.CharField(max_length=50)),
                ('Details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Created_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
