# Generated by Django 5.2 on 2025-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0009_courses_alter_student_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Fees',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='Batch',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Duration',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Timings',
            field=models.CharField(),
        ),
    ]
