# Generated by Django 5.2 on 2025-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0010_courses_fees_alter_courses_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Fees',
        ),
        migrations.AlterField(
            model_name='courses',
            name='Batch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Timings',
            field=models.CharField(max_length=50),
        ),
    ]
