# Generated by Django 5.2 on 2025-05-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0011_remove_courses_fees_alter_courses_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
