# Generated by Django 5.2 on 2025-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0012_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=50)),
                ('Timings', models.CharField(max_length=50)),
                ('Batch', models.CharField(max_length=50)),
                ('Details', models.TextField()),
            ],
        ),
    ]
