# Generated by Django 5.2 on 2025-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0013_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Fees',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
