# Generated by Django 5.2 on 2025-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0014_course_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Fees',
            field=models.CharField(default='₹', max_length=25),
        ),
    ]
