# Generated by Django 5.2 on 2025-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0015_alter_course_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Image',
            field=models.FileField(default='Add Image', upload_to=''),
        ),
    ]
