# Generated by Django 5.2 on 2025-05-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0016_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
