# Generated by Django 5.2 on 2025-05-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0017_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
    ]
