# Generated by Django 5.2 on 2025-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0018_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Image',
            new_name='Image_forBanner',
        ),
        migrations.AddField(
            model_name='course',
            name='Image_500x600',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
        migrations.AddField(
            model_name='course',
            name='Image_80x80',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
    ]
