# Generated by Django 5.2 on 2025-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0019_rename_image_course_image_forbanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Overview',
            field=models.TextField(blank=True),
        ),
    ]
