# Generated by Django 5.2 on 2025-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0020_course_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
