# Generated by Django 5.2 on 2025-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0021_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Image_forHome',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
    ]
