# Generated by Django 5.2 on 2025-05-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0022_course_image_forhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Comments', models.TextField(blank=True)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
