# Generated by Django 5.2 on 2025-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0023_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Rating',
            field=models.CharField(blank=True, null=True),
        ),
    ]
