# Generated by Django 5.2 on 2025-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0024_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_Image', models.ImageField(upload_to='')),
                ('feature_Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
