# Generated by Django 5.2 on 2025-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0025_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
