# Generated by Django 5.2 on 2025-05-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0026_misc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='Name',
            field=models.CharField(null=True),
        ),
    ]
