# Generated by Django 5.2 on 2025-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0027_alter_misc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='certifications_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='misc',
            name='rating_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
