# Generated by Django 5.2 on 2025-05-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0028_misc_certifications_image_misc_rating_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Is_First_Login',
            field=models.BooleanField(default=True),
        ),
    ]
