# Generated by Django 5.2 on 2025-05-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0030_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
