# Generated by Django 5.2 on 2025-05-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0031_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
    ]
