# Generated by Django 5.2 on 2025-05-11 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0032_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Scope.course'),
        ),
    ]
