# Generated by Django 5.2 on 2025-05-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0034_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
