# Generated by Django 5.2 on 2025-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0035_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Additional_Courses_Chosen',
            field=models.ManyToManyField(blank=True, to='Scope.course'),
        ),
    ]
