# Generated by Django 5.2 on 2025-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0036_student_additional_courses_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Additional_Courses_Chosen',
            field=models.ManyToManyField(blank=True, null=True, to='Scope.course'),
        ),
    ]
