# Generated by Django 5.2 on 2025-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0037_alter_student_additional_courses_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Profile_Image',
            field=models.ImageField(blank=True, default='student/default.png', null=True, upload_to='student/'),
        ),
    ]
