# Generated by Django 5.2 on 2025-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0038_alter_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc',
            name='certifications_Image',
        ),
        migrations.AddField(
            model_name='misc',
            name='default_Dash',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
