# Generated by Django 5.2 on 2025-05-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0039_remove_misc_certifications_image_misc_default_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='certifications_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
