# Generated by Django 5.2 on 2025-05-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0040_misc_certifications_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc',
            name='default_Dash',
        ),
    ]
