# Generated by Django 5.2 on 2025-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0041_remove_misc_default_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='default_Dash',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
