# Generated by Django 5.2 on 2025-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0042_misc_default_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='login_page',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='misc',
            name='sign_up_page',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
